apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/operator-type: non-standalone
  name: ovn-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OVNController is the Schema for the ovncontrollers API
      displayName: OVNController
      kind: OVNController
      name: ovncontrollers.ovn.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: OVNDBCluster is the Schema for the ovndbclusters API
      displayName: OVNDBCluster
      kind: OVNDBCluster
      name: ovndbclusters.ovn.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: OVNNorthd is the Schema for the ovnnorthds API
      displayName: OVNNorthd
      kind: OVNNorthd
      name: ovnnorthds.ovn.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to TLS
        displayName: TLS
        path: tls
      version: v1beta1
  description: OVN Operator
  displayName: OVN Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Network
  - Ovn
  links:
  - name: Ovn Operator
    url: https://github.com/openstack-k8s-operators/ovn-operator
  maturity: alpha
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
